name: Daily Tweet Bot

on:
  schedule:
    - cron: "40 16 * * *"  # 10:40 AM CST (16:40 UTC)
    - cron: "15 19 * * *"  # 01:15 PM CST (19:15 UTC)
    - cron: "30 21 * * *"  # 03:30 PM CST (21:30 UTC)
    - cron: "30 23 * * *"  # 05:30 PM CST (23:30 UTC)
    - cron: "30 2 * * *"   # 08:30 PM CST (02:30 UTC next day)
  workflow_dispatch:        # allow manual trigger

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tweet script
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python twitter_bot.py
